apiVersion: v2
name: voting
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.0"

dependencies:
- name: redis
  version: 15.5.4
  repository: https://charts.bitnami.com/bitnami
- name: postgresql #DB ver 14.1.0
  version: 11.0.4
  repository: https://charts.bitnami.com/bitnami
# - name: nfs-subdir-external-provisioner
#   # version: 4.0.11
#   version: 4.0.14
#   repository: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
# - name: aws-load-balancer-controller
#   version: 1.3.2
#   # version: 1.2.2
#   repository: https://aws.github.io/eks-charts
  # source: https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller
# - name: prometheus
#   version: 14.11.1
#   # version: 13.3.2
#   repository: https://prometheus-community.github.io/helm-charts