# ---
# # apiVersion: extensions/v1beta1
# apiVersion: networking.k8s.io/v1
# # apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: task-cluster
#   labels:
#     app: task
#     name: main
#   annotations:
#     kubernetes.io/ingress.class: alb
#     # required to use ClusterIP
#     alb.ingress.kubernetes.io/target-type: ip
#     # required to place on public-subnet
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/load-balancer-attributes: >-
#       routing.http.drop_invalid_header_fields.enabled=true,
#       routing.http2.enabled=true,
#       idle_timeout.timeout_seconds=60,
#       deletion_protection.enabled=false,
#       access_logs.s3.enabled=true,
#       access_logs.s3.bucket=cvtr-elb-logging,
#       access_logs.s3.prefix={{ .Values.global.env }}
#     alb.ingress.kubernetes.io/wafv2-acl-arn: ###WAFV2_ACL_ARN###
#     alb.ingress.kubernetes.io/tags: Environment={{ .Values.global.env }},Team=Devops
#     alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10
#     # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:366511911860:certificate/a0c0b58a-67a5-4fba-952b-65601a8be02f #eu-west-1.cvtr.io
#     alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:366511911860:certificate/2fc8c92d-8434-42d0-87e8-585316b7f5ad #cvtr.io
#     # redirect to port 80 to port 443
#     alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
#     # alb.ingress.kubernetes.io/actions.response-404: {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"404","messageBody":"Not Found yet"}}
# spec:
#   # tls:
#   # - hosts:
#   #     - https-example.foo.com
#   #   secretName: testsecret-tls
#   # rules:
#   # backend:
#   #   service:
#   #     name: response-404
#   #     port: use-annotation
#   rules:
#     #main ALB hostname with rules
#   - host: "test.{{ .Values.global.domain.name }}"
#     http:
#       paths:
#       - backend:
#           service:
#             name: ssl-redirect
#             port:
#               name: use-annotation
#         path: /
#         pathType: Prefix
#       - backend:
#           service:
#             name: task
#             port:
#               number: 443
#         path: //saml*
#         pathType: ImplementationSpecific
#       - backend:
#           service:
#             name: dashboard
#             port:
#               number: 443
#         path: /
#         pathType: Prefix
