---
apiVersion: v1
kind: Service
metadata:
  # annotations:
  #   alb.ingress.kubernetes.io/healthcheck-path: "/index.html"
  #   alb.ingress.kubernetes.io/successCodes: "200"
  #   alb.ingress.kubernetes.io/backend-protocol: "HTTPS"
  name: result-app
  labels:
    app: {{ .Release.Name }}-{{ .Values.name }}
    tier: frontend
    # tier: backend
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.name }}
    tier: frontend
    # tier: backend
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.image.port }}
    name: "from-{{ .Values.service.port }}-to-{{ .Values.image.port }}"
  - protocol: TCP
    port: {{ .Values.service.port2 }}
    targetPort: {{ .Values.image.port2 }}
    name: "from-{{ .Values.service.port2 }}-to-{{ .Values.image.port2 }}"
